name: Test Action

on: push

jobs:
  get_sha:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: matheusraz/ref-sha@staging/v6
      id: get_sha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ref: staging/v6
    
    - name: Result
      run: echo "${{ steps.get_sha.outputs.sha }}"